'''
Returns a flat list of all the keys in a flat dictionary.

Use dict.keys() to return the keys in the given dictionary. Return a list() of the previous result.
'''
def keys_only(flat_dict):
    return list(flat_dict.keys())
ages = {
    "Peter": 10,
    "Isabel": 11,
    "Anna": 9,
}
print(keys_only(ages))


'''
map_values
Creates an object with the same keys as the provided object and
    values generated by running the provided function for each value.

Use dict.keys() to iterate over the object's keys, 
assigning the values produced by fn to each key of a new object.
'''
def map_values(obj, fn):
    ret = {}
    for k in obj.keys():
        ret[k] = fn(obj[k])
    return ret

users = {
  'fred': { 'user': 'fred', 'age': 40 },
  'pebbles': { 'user': 'pebbles', 'age': 1 }
}
print(map_values(users, lambda u: u['age']))

def values_only(dict):
    return list(dict.values())
